spring.application.name=recomendacionApp

# CONEXIÓN A LA BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL:${DB_URL_DOCKER}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SEGURIDAD Y API EXTERNA
jwt.secret=${JWT_SECRET}
tmdb.base-url=${TMDB_BASE_URL}
tmdb.api-key=${TMDB_API_KEY}

# Evita conflicto conocido entre springdoc y HATEOAS
springdoc.enable-hateoas=false